### ISSUE TITLE
Tomcat files permission problems when running on GKE

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-docker#78]
The "latest" version of the ESGF containers does not run correctly on GKE (while it seems to be running correctly on AWS EKS and Minikibe). Specifically, all containers that inherit from the esgfhub/tomcat:latest image show some form of file permission and do not start. See following errors.

**Comment by LucaCinquini** [comment]
IdP

31-Jul-2018 18:30:41.276 SEVERE [Catalina-startStop-1] org.apache.catalina.valves.AccessLogValve.open Failed to open access log file [/usr/local/tomcat/logs/localhost_access_log.2018-07-31.txt]
 java.io.FileNotFoundException: /usr/local/tomcat/logs/localhost_access_log.2018-07-31.txt (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.apache.catalina.valves.AccessLogValve.open(AccessLogValve.java:651)
        at org.apache.catalina.valves.AccessLogValve.startInternal(AccessLogValve.java:685)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:182)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:955)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by LucaCinquini** [comment]
TDS

ESGF_TDS_PORT_8080_TCP_PROTO=tcp
ESGF_COG_SERVICE_PORT_HTTP=8000
ESGF_SLCS_URL=https://esgf.104.154.71.234.xip.io/esgf-slcs
ESGF_PROXY_PORT_80_TCP_PROTO=tcp
ESGF_DATABASE_USER=dbsuper
[INFO] Interpolating THREDDS web.xml
grep: /usr/local/tomcat/webapps/thredds/WEB-INF/web.xml: Permission denied

and:

1-Jul-2018 20:44:35.783 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
31-Jul-2018 20:44:35.785 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.30
31-Jul-2018 20:44:35.795 SEVERE [Catalina-startStop-1] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/usr/local/tomcat/conf/Catalina/localhost]
31-Jul-2018 20:44:35.802 SEVERE [Catalina-startStop-1] org.apache.catalina.valves.AccessLogValve.open Failed to open access log file [/usr/local/tomcat/logs/localhost_access_log.2018-07-31.txt]
 java.io.FileNotFoundException: /usr/local/tomcat/logs/localhost_access_log.2018-07-31.txt (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.apache.catalina.valves.AccessLogValve.open(AccessLogValve.java:651)
        at org.apache.catalina.valves.AccessLogValve.startInternal(AccessLogValve.java:685)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:182)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:955)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by LucaCinquini** [comment]
ORP

ESGF_IDP_HOSTNAME=esgf.35.225.81.3.xip.io
ESGF_PEER_GROUP=esgf-test
ESGF_PROXY_PORT_443_TCP=tcp://10.19.245.153:443
ESGF_POSTGRES_ESGCET_PORT_5432_TCP_PROTO=tcp
ESGF_POSTGRES_ESGCET_SERVICE_HOST=10.19.255.76
ESGF_INDEX_NODE_HOSTNAME=esgf.35.225.81.3.xip.io
ESGF_ORP_PORT_8080_TCP=tcp://10.19.245.38:8080
ESGF_IDP_NODE_SERVICE_HOST=10.19.252.104
ESGF_PROXY_SERVICE_PORT=443
ESGF_PROXY_PORT_80_TCP=tcp://10.19.245.153:80
ESGF_DATABASE_HOST=esgf-postgres-esgcet
ESGF_PROXY_PORT_443_TCP_ADDR=10.19.245.153
ESGF_SLCS_URL=https://esgf.35.225.81.3.xip.io/esgf-slcs
ESGF_ORP_PORT_8080_TCP_ADDR=10.19.245.38
ESGF_PROXY_PORT_80_TCP_PROTO=tcp
ESGF_DATABASE_USER=dbsuper
[INFO] Checking environment
[INFO] Creating PKCS12 bundle for host certificate and private key
pkcs12: Cannot open output file /usr/local/tomcat/conf/hostcert.p12, Permission denied
pkcs12: Use -help for summary.

**Comment by LucaCinquini** [comment]
I think we might run into the "layering" problem that is reported by several users here:

https://github.com/docker-library/tomcat/issues/35

Of the proposed solutions, the following worked for me:

a) Use a very specific Tomcat version - before the permissions were changed:
tomcat:8.0.36-jre8
Note that tomcat:8.0.53-jre8
won't work

b) Instead of using the official Tomcat image, start from ubuntu:latest and install Tomcat, eventually switching to run Tomcat as non-root. This will also work.

**Comment by mkjpryor-stfc** [comment]
I have not seen this issue on GKE or Minikube. Closing as wontfix.
